### ISSUE TITLE
El titulo "Elección de A priori" deberia cambiarse,

### ISSUE THREAD

**Issue by harpomaxx** [MrtC101/spatial-data-mining#28]
Ahi en realidad habria que cambiar el titulo, ya que simplemente explicas algunas de las características de apriori.
Para mi el titulo seria: Algoritmo A priori para extracción de reglas.

Entonces cambiaria la introducción a la seccion para que diga algo asi como:
> Para este trabajo se decidió utilizar el algoritmo A priori. Se tratar de una algoritmo que hacer bla bla bla. Su elección responde a tal ta tal

**Comment by harpomaxx** [comment]
No veo que se haya efectivamente solucionado este issue. En el documento sigue figurando el titulo Elección a Prior

**Comment by MrtC101** [comment]
Ya se actualizo el informe en la rama develop donde este issue el titulo se ha cambiado.
