### ISSUE TITLE
Conclusiones (1)

### ISSUE THREAD

**Issue by harpomaxx** [MrtC101/spatial-data-mining#32]
Revisar conclusiones. Palabras mal escritas. Errores de puntuación.

En las conclusiones decís que el tiempo es alto para el procesamiento, pero no veo ninguna metrica que indique eso. Entonces como que queda descolgado.

**Comment by MrtC101** [comment]
Se añadió el tiempo de preprocesamiento que tomo cada experimento. Aun así no creo que concluir con que el tiempo de ejecución sea alto este correcto
