### ISSUE TITLE
Armar presentacion para rendir la materia.

### ISSUE THREAD

**Issue by harpomaxx** [MrtC101/spatial-data-mining#43]
Para la defensa del proyecto de la materia. se deberá preparar una presentación de no mas de 15 minutos de duracion.
En dicha presentación deberán indicarse.

1. Motivación
2. Enfoque utilizado
3. Resultados.
4. Conclusiones.

Sobre el enfoque utilizando, no pretendo nada largo, 1 o 2 slides a lo sumo. Ya que mucha de la explicación se encuentra en el documento del proyecto.

Si espero mucha claridad a la hora de presentar los resultados. El 70% de la presentación deberia ir dedicada a los resultados.

**Comment by MrtC101** [comment]
Ya se ha creado una presentación
